### ISSUE TITLE
brew install phantomjs failed

### ISSUE THREAD

**Issue by micholi** [learn-co-curriculum/your-own-js-and-css-in-rails#11]
I received the error about phantomjs not being on my system. I tried brew install phantomjs as suggested in the Readme, however it resulted in a bunch of errors and failed to install. I found the following workaround, which fixed the issues I was having, and I wanted to share as an alternative in case anyone else has trouble installing.

npm install phantom phantomjs -g

**Comment by sgharms** [comment]
I would recommend you to prefer doing the `brew install` method. **IF** this fails, it suggests, something in your developer environment needs help. I'd be wary of not facing the pain to get this working because it's _highly likely_ to foul you up somewhere _else_ later down the road. Further `brew`'s purpose is "add programs to my software through a really elegant installer."

In contrast, `npm` best practice is to operate on a per-project architecture. The `--global` or `-g` flag basically tells npm to move from its default modality (per project) and to instead put the binary in a global OS location. This can lead to some confusing (and surprising) behavior. Developers have learned that segregating environments is a good idea (Ruby's Bundler, NPM, Python's virtualenv all do this).

End result: _both_ means provide you a `phantomjs` program, but I'd discourage this mode. Nevertheless, I have to 👏 your creativity.
